version: '2'
services:

  # data only container pattern
  datatest:
    extends:
      file: docker-compose-common.yml
      service: datatest

  # runs the tests against docker-compose-teststack.yml
  testhost:
    image: muccg/rdrf-dev
    command: runtests
    environment:
      - DBUSER=rdrfapp
      - WAIT_FOR_DB=1
      - WAIT_FOR_REPORTING=1
      - WAIT_FOR_RUNSERVER=1
      - WAIT_FOR_MONGO=1
    volumes_from:
      - datatest
    external_links:
      - rdrf_dbtest_1:db
      - rdrf_runservertest_1:web
      - rdrf_mongotest_1:mongo
        #- rdrf_reportingtest_1:reporting
