version: '2'
services:

  #
  dataselenium:
    extends:
      file: docker-compose-common.yml
      service: dataselenium

  # runs the selenium tests against docker-compose-teststack.yml
  seleniumtesthost:
    image: muccg/rdrf-dev
    command: selenium
    environment:
      - DBUSER=rdrfapp
      - WAIT_FOR_DB=1
      - WAIT_FOR_MONGO=1
      - WAIT_FOR_HOST_PORT=8443
      - DEPLOYMENT=prod
    volumes_from:
      - dataselenium
    external_links:
      - rdrf_uwsgiprod_1:web
      - rdrf_dbprod_1:db
      - rdrf_seleniumhub_1:hub
      - rdrf_mongoprod_1:mongo
